---
# Example configuration keys given below.
# All of these can be overridden via message
#
debug: true
loop_delay: 60
enabled: true
user_name: email@example.com
passwd: password
# reply_to: someone@supplier.com
recipients:
- name: Someone Else
  email: someone.else@client.com
templates:
  default:
    subject: Shipping Dates Updated
    text: |
      The shipping information for an order has been updated.

      PO Number : {{po_number}}
      Product   : {{product_name}}
      Method    : {{ship_method}}
      Ship Date : {{ship_date}}
      Comment   : {{comment}}

    html: |
      <html><head></head><body><p>The shipping information for an order has been updated.</p>
      <ul>
      <li>PO Number: {{po_number}}</li>
      <li>Product: {{product_name}}</li>
      <li>Method: {{ship_method}}</li>
      <li>Ship Date: {{ship_date}}</li>
      <li>Comment: {{comment}}</li>
      </ul>
      </body></html>
#   template_name:
#     subject: Email Subject Line
#     text_file: path/to/text/template.txt
#     text: |
#       multi-line text template for email
#     html_file: path/to/html/template.html
#     html: |
#       multi-line html template for email
    tokens:
# token: value
      po_number: "msg.data[0]['purchaseordernumber']"
      product_name: "msg.data[0]['productname']"
      ship_method: "msg.data[0]['shipmethod']"
      ship_date: "msg.data[0]['shipdate']"
      comment: "msg.data[0]['comment']"
# attachments:
#   attachment_name: path/to/attachment
#   other_attachment: path/to/other/attachment
#
