# ---
# user_name: someone@someplace.com
# passwd: apasswordhere
# sender: someone@supplier.com
---
enabled: true
loop_delay: 60.0
debug: true
user_name: nodallydemo@gmail.com
passwd: KarButtShoE4977
sender: dougs@nodally.com
children:
- nm2
