# ---
# user_name: someone@someplace.com
# passwd: apasswordhere
# sender: someone@supplier.com
---
enabled: true
loop_delay: 60.0
debug: true
user_name: email@example.com
passwd: password
sender: recipient@example.com
children: []
